[package]
name = "kvs"
version = "0.1.0"
authors = ["Sean <thisseanzhang@gmail.com>"]
description = "A key-value store"
edition = "2021"

[dependencies]

[dependencies.clap]
version = "4.0.29"
features = [ "derive" ]

[dev-dependencies]
assert_cmd = "2.0.7"
predicates = "2.1.4"
