[package]
name = "c_10_lifetime_method"
version = "0.1.0"
authors = ["ThisSeanZhang <thisseanzhang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
