[workspace]
members = [
    "post-01",
    "post-02",
    "post-03",
    "post-04",
    "post-05",
    "post-06",
    "post-07",
    "post-08",
    "post-09",
    "post-10",
    "post-11",
    "post-12",
]
resolver = "2"



# [profile.dev]
# panic = "abort"

# [profile.release]
# panic = "abort"
