[workspace]
members = [
    "post-01",
    "post-02",
    "post-03",
    "post-04",
    "post-05",
    "post-06",
]
resolver = "2"



# [profile.dev]
# panic = "abort"

# [profile.release]
# panic = "abort"
